
//
// Copyright (c) 1992-2020 Wo Of Ideafarm.  All rights reserved.  See IDEAFARM.COM for permitted uses.
//
// This proprietary software was crafted at great expense and with great hardship by one man.  It took 28 years.
// Respecting the rights of other people is an important part of empowering one another.
//

/*
\<A HREF=\"5.005f001.1.0.html\"\>definition\</A\>
it is illegal to refer to this symbol in the definition of an adam
*/
/**/
/*1*//*preliminary declarations of class and struct identifiers ; class and struct symbolic constants*//*1*/

//ALPHABETICAL
//THE SHORT CODES AT THE END OF EACH LINE ARE USED TO CREATE MANGLED WORDS FOR SOIL (tm)
//DO NOT CHANGE THE MANGLE CODES (E.G. "A1").  CHANGING THESE CODES WILL BREAK ALL SOIL (tm) CODE THAT USES THEM

struct /*ff*/argS/*ff*/                         ; /*ff*//**//*ff*/
class  /*ff*/arrayC/*ff*/                       ; /*ff*//**//*ff*/
class  /*ff*/batonBoxC/*ff*/                    ; /*ff*//**//*ff*/
class  /*ff*/batonC/*ff*/                       ; /*ff*//**//*ff*/
class  /*ff*/boxC/*ff*/                         ; /*ff*//**//*ff*/
struct /*ff*/branchDataOldS/*ff*/               ; /*ff*//**//*ff*/
struct /*ff*/branchesOldS/*ff*/                 ; /*ff*//**//*ff*/
struct /*ff*/branchHeaderOldS/*ff*/             ; /*ff*//**//*ff*/
class  /*ff*/bufferC/*ff*/                      ; /*ff*//**//*ff*/
class  /*ff*/busC/*ff*/                         ; /*ff*//**//*ff*/
class  /*ff*/carC/*ff*/                         ; /*ff*//**//*ff*/
class  /*ff*/cC/*ff*/                           ; /*ff*//**//*ff*/
struct /*ff*/cyrcleOldHeaderS/*ff*/             ; /*ff*//**//*ff*/
struct /*ff*/count2S/*ff*/                      ; /*ff*//**//*ff*/
struct /*ff*/count3S/*ff*/                      ; /*ff*//**//*ff*/
struct /*ff*/count4S/*ff*/                      ; /*ff*//**//*ff*/
struct /*ff*/count5S/*ff*/                      ; /*ff*//**//*ff*/
struct /*ff*/count6S/*ff*/                      ; /*ff*//**//*ff*/
struct /*ff*/count7S/*ff*/                      ; /*ff*//**//*ff*/
struct /*ff*/count8S/*ff*/                      ; /*ff*//**//*ff*/
struct /*ff*/count9S/*ff*/                      ; /*ff*//**//*ff*/
class  /*ff*/countTC/*ff*/                      ; /*ff*//**//*ff*/
class  /*ff*/cryC/*ff*/                         ; /*ff*//**//*ff*/
class  /*ff*/dictionary1C/*ff*/                 ; /*ff*//**//*ff*/
struct /*ff*/dnsMsgHeaderS/*ff*/                ; /*ff*//**//*ff*/
struct /*ff*/dnsResourceMiddleS/*ff*/           ; /*ff*//**//*ff*/
struct /*ff*/dropNoteS/*ff*/                    ; /*ff*//**//*ff*/
class  /*ff*/etherC/*ff*/                       ; /*ff*//*a*//*ff*/
struct /*ff*/fileOpenS/*ff*/                    ; /*ff*//**//*ff*/
struct /*ff*/fireAllS/*ff*/                     ; /*ff*//**//*ff*/
class  /*ff*/fylesC/*ff*/                       ; /*ff*//**//*ff*/
class  /*ff*/processGlobalBeginC/*ff*/          ; /*ff*//**//*ff*/
class  /*ff*/processGlobalEndC/*ff*/            ; /*ff*//**//*ff*/
class  /*ff*/gloSecurityGC/*ff*/                ; /*ff*//**//*ff*/
struct /*ff*/grabAnnotatedS/*ff*/               ; /*ff*//**//*ff*/
struct /*ff*/grabNotesS/*ff*/                   ; /*ff*//**//*ff*/
class  /*ff*/grabC/*ff*/                        ; /*ff*//**//*ff*/
struct /*ff*/grabStatS/*ff*/                    ; /*ff*//**//*ff*/
struct /*ff*/grabWantOldS/*ff*/                 ; /*ff*//**//*ff*/
struct /*ff*/grabWantS/*ff*/                    ; /*ff*//**//*ff*/
class  /*ff*/handleC/*ff*/                      ; /*ff*//*b*//*ff*/
class  /*ff*/handle1000C/*ff*/                  ; /*ff*//*b*//*ff*/
class  /*ff*/handle0100C/*ff*/                  ; /*ff*//*b*//*ff*/
class  /*ff*/handle1100C/*ff*/                  ; /*ff*//*b*//*ff*/
class  /*ff*/handle0010C/*ff*/                  ; /*ff*//*b*//*ff*/
class  /*ff*/handle1010C/*ff*/                  ; /*ff*//*b*//*ff*/
class  /*ff*/handle0110C/*ff*/                  ; /*ff*//*b*//*ff*/
class  /*ff*/handle1110C/*ff*/                  ; /*ff*//*b*//*ff*/
class  /*ff*/handle0011C/*ff*/                  ; /*ff*//*b*//*ff*/
class  /*ff*/handle1011C/*ff*/                  ; /*ff*//*b*//*ff*/
class  /*ff*/handle0111C/*ff*/                  ; /*ff*//*b*//*ff*/
class  /*ff*/handle1111C/*ff*/                  ; /*ff*//*b*//*ff*/
class  /*ff*/handle2C/*ff*/                     ; /*ff*//*b*//*ff*/
class  /*ff*/handle1C/*ff*/                     ; /*ff*//*b*//*ff*/
class  /*ff*/neverUsedC/*ff*/                   ; /*ff*//**//*ff*/
class  /*ff*/hoodC/*ff*/                        ; /*ff*//**//*ff*/
struct /*ff*/homeS/*ff*/                        ; /*ff*//**//*ff*/
class  /*ff*/ap_artmentOldC/*ff*/               ; /*ff*//**//*ff*/
class  /*ff*/ifFileNameC/*ff*/                  ; /*ff*//**//*ff*/
class  /*ff*/imageExeDllC/*ff*/                 ; /*ff*//**//*ff*/
struct /*ff*/infoBoxGetPutS/*ff*/               ; /*ff*//**//*ff*/
struct /*ff*/infoDisk1aS/*ff*/                  ; /*ff*//**//*ff*/
struct /*ff*/infoDisk1bS/*ff*/                  ; /*ff*//**//*ff*/
struct /*ff*/infoDisk1S/*ff*/                   ; /*ff*//**//*ff*/
struct /*ff*/infoDiskS/*ff*/                    ; /*ff*//**//*ff*/
struct /*ff*/infoFileS/*ff*/                    ; /*ff*//**//*ff*/
struct /*ff*/killSocketS/*ff*/                  ; /*ff*//**//*ff*/
struct /*ff*/mainRefsS/*ff*/                    ; /*ff*//**//*ff*/
struct /*ff*/mainS/*ff*/                        ; /*ff*//**//*ff*/
class  /*ff*/mapC/*ff*/                         ; /*ff*//**//*ff*/
class  /*ff*/maxC/*ff*/                         ; /*ff*//**//*ff*/
struct /*ff*/monitorReplyOldS/*ff*/             ; /*ff*//**//*ff*/
struct /*ff*/monQueryReplyS/*ff*/               ; /*ff*//**//*ff*/
class  /*ff*/napkinHeaderS/*ff*/                ; /*ff*//*c*//*ff*/
class  /*ff*/napkinC/*ff*/                      ; /*ff*//*c*//*ff*/
class  /*ff*/netC/*ff*/                         ; /*ff*//**//*ff*/
class  /*ff*/newsC/*ff*/                        ; /*ff*//**//*ff*/
struct /*ff*/newsKnowS/*ff*/                    ; /*ff*//**//*ff*/
class  /*ff*/nicNameC/*ff*/                     ; /*ff*//*d*//*ff*/
class  /*ff*/idPortC/*ff*/                      ; /*ff*//*r*//*ff*/
class  /*ff*/nicNamesC/*ff*/                    ; /*ff*//**//*ff*/
class  /*ff*/nicNamesNearbyOldC/*ff*/           ; /*ff*//**//*ff*/
class  /*ff*/osFileNameC/*ff*/                  ; /*ff*//**//*ff*/
class  /*ff*/pczC/*ff*/                         ; /*ff*//**//*ff*/
struct /*ff*/peekS/*ff*/                        ; /*ff*//**//*ff*/
struct /*ff*/plateS/*ff*/                       ; /*ff*//**//*ff*/
class  /*ff*/postOldC/*ff*/                     ; /*ff*//**//*ff*/
class  /*ff*/pricerC/*ff*/                      ; /*ff*//**//*ff*/
class  /*ff*/psttOldC/*ff*/                     ; /*ff*//**//*ff*/
struct /*ff*/queryTimeRemainingS/*ff*/          ; /*ff*//**//*ff*/
class  /*ff*/ranUniC/*ff*/                      ; /*ff*//**//*ff*/
struct /*ff*/rCacheS/*ff*/                      ; /*ff*//**//*ff*/
struct /*ff*/restartC/*ff*/                     ; /*ff*//**//*ff*/
class  /*ff*/sCountC/*ff*/                      ; /*ff*//**//*ff*/
struct /*ff*/serverInfo1S/*ff*/                 ; /*ff*//**//*ff*/
struct /*ff*/serverInfo2S/*ff*/                 ; /*ff*//**//*ff*/
class  /*ff*/setThirdC/*ff*/                    ; /*ff*//**//*ff*/
struct /*ff*/sharedMemInfoS/*ff*/               ; /*ff*//**//*ff*/
class  /*ff*/signC/*ff*/                        ; /*ff*//*f*//*ff*/
class  /*ff*/grabMemorySpaceC/*ff*/                ; /*ff*//**//*ff*/
class  /*ff*/backGrabMemorySpaceC/*ff*/            ; /*ff*//**//*ff*/
class  /*ff*/sleepC/*ff*/                       ; /*ff*//**//*ff*/
class  /*ff*/socketC/*ff*/                      ; /*ff*//*g*//*ff*/
class  /*ff*/soulC/*ff*/                        ; /*ff*//*h*//*ff*/
class  /*ff*/sqMatrixOldC/*ff*/                 ; /*ff*//**//*ff*/
class  /*ff*/stackC/*ff*/                       ; /*ff*//*i*//*ff*/
struct /*ff*/strokeModeS/*ff*/                  ; /*ff*//**//*ff*/
struct /*ff*/strokeS/*ff*/                      ; /*ff*//*4*//*ff*/
class  /*ff*/switchC/*ff*/                      ; /*ff*//*k*//*ff*/
class  /*ff*/switchStackC/*ff*/                 ; /*ff*//*l*//*ff*/
class  /*ff*/tableC/*ff*/                       ; /*ff*//*m*//*ff*/
struct /*ff*/taskS/*ff*/                        ; /*ff*//**//*ff*/
class  /*ff*/tellC/*ff*/                        ; /*ff*//**//*ff*/
struct /*ff*/tellInfoSysExceptionS/*ff*/           ; /*ff*//**//*ff*/
struct /*ff*/tellInfoSys_grabC_S/*ff*/             ; /*ff*//**//*ff*/
struct /*ff*/tellInfoSysLifiS/*ff*/                ; /*ff*//**//*ff*/
struct /*ff*/tellInfoSysNapkinS/*ff*/              ; /*ff*//**//*ff*/
class  /*ff*/testWaterC/*ff*/                   ; /*ff*//**//*ff*/
class  /*ff*/textC/*ff*/                        ; /*ff*//**//*ff*/
class  /*ff*/textIdFileC/*ff*/                  ; /*ff*//**//*ff*/
class  /*ff*/thirdC/*ff*/                       ; /*ff*//*n*//*ff*/
class  /*ff*/threadCheckC/*ff*/                 ; /*ff*//**//*ff*/
class  /*ff*/thugC/*ff*/                        ; /*ff*//**//*ff*/
struct /*ff*/timeS/*ff*/                        ; /*ff*//**//*ff*/
struct /*ff*/timeZoneSpecS/*ff*/                ; /*ff*//**//*ff*/
struct /*ff*/tinS/*ff*/                         ; /*ff*//*o*//*ff*/
struct /*ff*/tinTallyS/*ff*/                    ; /*ff*//**//*ff*/
struct /*ff*/tlsStackFrameLocationS/*ff*/       ; /*ff*//**//*ff*/
struct /*ff*/tlsStackFrameS/*ff*/               ; /*ff*//**//*ff*/
struct /*ff*/tlsStackFrameNoTlsS/*ff*/          ; /*ff*//**//*ff*/
class  /*ff*/treeOldC/*ff*/                     ; /*ff*//*p*//*ff*/
class  /*ff*/upDnC/*ff*/                        ; /*ff*//**//*ff*/
class  /*ff*/vectorOldC/*ff*/                   ; /*ff*//**//*ff*/
struct /*ff*/vmRegionS/*ff*/                    ; /*ff*//**//*ff*/
class  /*ff*/windowOldC/*ff*/                   ; /*ff*//*q*//*ff*/
class  /*ff*/zapC/*ff*/                         ; /*ff*//**//*ff*/
class  /*ff*/soixlOldSpaceC/*ff*/               ; /*ff*//**//*ff*/
class  /*ff*/idPortTimeC/*ff*/                  ; /*ff*//**//*ff*/
class  /*ff*/relayC/*ff*/                       ; /*ff*//**//*ff*/
class  /*ff*/spouseC/*ff*/                      ; /*ff*//**//*ff*/
class  /*ff*/momC/*ff*/                         ; /*ff*//**//*ff*/
class  /*ff*/dadC/*ff*/                         ; /*ff*//**//*ff*/
class  /*ff*/bitsC/*ff*/                        ; /*ff*//**//*ff*/
class  /*ff*/staticC/*ff*/                      ; /*ff*//**//*ff*/
class  /*ff*/parameterC/*ff*/                   ; /*ff*//**//*ff*/
class  /*ff*/sCountFromPostC/*ff*/              ; /*ff*//**//*ff*/
struct  /*ff*/osTextBaseS/*ff*/                 ; /*ff*//**//*ff*/
class  /*ff*/osTextC/*ff*/                      ; /*ff*//**//*ff*/
class  /*ff*/footC/*ff*/                        ; /*ff*//**//*ff*/
struct /*ff*/lowThreadS/*ff*/                   ; /*ff*//**//*ff*/
class  /*ff*/tallyC/*ff*/                       ; /*ff*//**//*ff*/
class  /*ff*/poopC/*ff*/                        ; /*ff*//**//*ff*/
class  /*ff*/scoopC/*ff*/                       ; /*ff*//**//*ff*/
struct  /*ff*/mapCTS/*ff*/                      ; /*ff*//**//*ff*/
class   /*ff*/mapCTC/*ff*/                      ; /*ff*//**//*ff*/
class   /*ff*/pauseC/*ff*/                      ; /*ff*//**//*ff*/
struct /*ff*/strokingFrameS/*ff*/               ; /*ff*//**//*ff*/
class   /*ff*/xrayC/*ff*/                       ; /*ff*//**//*ff*/
class   /*ff*/arrayOldC/*ff*/                    ; /*ff*//**//*ff*/
class   /*ff*/vTextC/*ff*/                      ; /*ff*//**//*ff*/
class   /*ff*/staqC/*ff*/                       ; /*ff*//**//*ff*/
class   /*ff*/tcButtonC/*ff*/                   ; /*ff*//**//*ff*/
class   /*ff*/paperOldC/*ff*/                   ; /*ff*//**//*ff*/
class   /*ff*/tcPromptC/*ff*/                   ; /*ff*//**//*ff*/
class   /*ff*/tcSliderC/*ff*/                   ; /*ff*//**//*ff*/
class   /*ff*/tcButtonQuitC/*ff*/               ; /*ff*//**//*ff*/
class   /*ff*/blobC/*ff*/                       ; /*ff*//**//*ff*/
class   /*ff*/treeC/*ff*/                       ; /*ff*//**//*ff*/
class   /*ff*/eyeOldC/*ff*/                     ; /*ff*//**//*ff*/
class   /*ff*/pulpOldC/*ff*/                    ; /*ff*//**//*ff*/
class   /*ff*/eyePulpOldC/*ff*/                 ; /*ff*//**//*ff*/
class   /*ff*/winPulpOldC/*ff*/                 ; /*ff*//**//*ff*/
class   /*ff*/backOldC/*ff*/                    ; /*ff*//**//*ff*/
class   /*ff*/sadamC/*ff*/                      ; /*ff*//**//*ff*/
class   /*ff*/frPaperC/*ff*/                    ; /*ff*//**//*ff*/
struct  /*ff*/cmdFlashS/*ff*/                   ; /*ff*//**//*ff*/
struct  /*ff*/mapPaperToBackS/*ff*/             ; /*ff*//**//*ff*/
struct  /*ff*/mapPaperToEyeOldS/*ff*/           ; /*ff*//**//*ff*/
class   /*ff*/bitmapOldC/*ff*/                  ; /*ff*//**//*ff*/
class   /*ff*/papersOldC/*ff*/                  ; /*ff*//**//*ff*/
struct  /*ff*/mColRowMinMaxS/*ff*/              ; /*ff*//**//*ff*/
class   /*ff*/threadC/*ff*/                     ; /*ff*//**//*ff*/
class   /*ff*/httpServerC/*ff*/                 ; /*ff*//**//*ff*/
struct  /*ff*/httpServerC_arg1S/*ff*/           ; /*ff*//**//*ff*/
struct  /*ff*/httpServerC_arg2S/*ff*/           ; /*ff*//**//*ff*/
class   /*ff*/sessionsC/*ff*/                   ; /*ff*//**//*ff*/
class   /*ff*/sessionC/*ff*/                    ; /*ff*//**//*ff*/
class   /*ff*/plateC/*ff*/                      ; /*ff*//**//*ff*/
struct  /*ff*/httpReplyS/*ff*/                  ; /*ff*//**//*ff*/
struct  /*ff*/sockOdometerS/*ff*/               ; /*ff*//**//*ff*/
struct  /*ff*/processGlobal1S/*ff*/             ; /*ff*//**//*ff*/
struct  /*ff*/processGlobal2S/*ff*/             ; /*ff*//**//*ff*/
struct  /*ff*/processGlobal3S/*ff*/             ; /*ff*//**//*ff*/
struct  /*ff*/processGlobal4S/*ff*/             ; /*ff*//**//*ff*/
struct  /*ff*/processGlobal5S/*ff*/             ; /*ff*//**//*ff*/
struct  /*ff*/processGlobal6S/*ff*/             ; /*ff*//**//*ff*/
struct  /*ff*/processGlobal7S/*ff*/             ; /*ff*//**//*ff*/
struct  /*ff*/adamGlobal1S/*ff*/                ; /*ff*//**//*ff*/
struct  /*ff*/adamGlobal2S/*ff*/                ; /*ff*//**//*ff*/
struct  /*ff*/adamGlobal3S/*ff*/                ; /*ff*//**//*ff*/
struct  /*ff*/adamGlobal4S/*ff*/                ; /*ff*//**//*ff*/
struct  /*ff*/adamGlobal5S/*ff*/                ; /*ff*//**//*ff*/
struct  /*ff*/adamGlobal6S/*ff*/                ; /*ff*//**//*ff*/
struct  /*ff*/dictionaryFileTitleS/*ff*/        ; /*ff*//**//*ff*/
class   /*ff*/sourceC/*ff*/                     ; /*ff*//**//*ff*/
class   /*ff*/ag1_backOldC_C/*ff*/              ; /*ff*//**//*ff*/
class   /*ff*/ag1_bitsC_C/*ff*/                 ; /*ff*//**//*ff*/
class   /*ff*/ag1_etherC_C/*ff*/                ; /*ff*//**//*ff*/
class   /*ff*/ag1_grabNotesS_C/*ff*/            ; /*ff*//**//*ff*/
class   /*ff*/ag1_grabC_C/*ff*/                 ; /*ff*//**//*ff*/
class   /*ff*/ag1_lexC_C/*ff*/                  ; /*ff*//**//*ff*/
class   /*ff*/ag1_masterOldC_C/*ff*/               ; /*ff*//**//*ff*/
class   /*ff*/ag1_neverUsedC_C/*ff*/            ; /*ff*//**//*ff*/
class   /*ff*/ag1_paperOldC_C/*ff*/             ; /*ff*//**//*ff*/
class   /*ff*/ag1_pulpOldC_C/*ff*/              ; /*ff*//**//*ff*/
class   /*ff*/ag1_relayC_C/*ff*/                ; /*ff*//**//*ff*/
class   /*ff*/ag1_rootWordC_C/*ff*/             ; /*ff*//**//*ff*/
class   /*ff*/ag3_socketC_C/*ff*/               ; /*ff*//**//*ff*/
class   /*ff*/ag1_soulC_C/*ff*/                 ; /*ff*//**//*ff*/
class   /*ff*/ag1_soixlOldSpaceC_C/*ff*/        ; /*ff*//**//*ff*/
class   /*ff*/ag1_stackC_C/*ff*/                ; /*ff*//**//*ff*/
class   /*ff*/ag1_strokeS_C/*ff*/               ; /*ff*//**//*ff*/
class   /*ff*/ag1_switchC_C/*ff*/               ; /*ff*//**//*ff*/
class   /*ff*/ag1_tableC_C/*ff*/                ; /*ff*//**//*ff*/
class   /*ff*/ag1_thirdC_C/*ff*/                ; /*ff*//**//*ff*/
class   /*ff*/ag1_thugC_C/*ff*/                 ; /*ff*//**//*ff*/
class   /*ff*/ag1_windowOldC_C/*ff*/            ; /*ff*//**//*ff*/
class   /*ff*/masterOldC/*ff*/                     ; /*ff*//**//*ff*/
class   /*ff*/marketC/*ff*/                     ; /*ff*//**//*ff*/
class   /*ff*/adamC/*ff*/                       ; /*ff*//**//*ff*/
class   /*ff*/x0SwitchStackC/*ff*/              ; /*ff*//**//*ff*/
class   /*ff*/xSwitchStackC/*ff*/               ; /*ff*//**//*ff*/
class   /*ff*/rangeC/*ff*/                      ; /*ff*//**//*ff*/
class   /*ff*/aptC/*ff*/                        ; /*ff*//**//*ff*/
struct  /*ff*/aptNameOldS/*ff*/                 ; /*ff*//**//*ff*/
struct  /*ff*/ipMapPortS/*ff*/                  ; /*ff*//**//*ff*/
struct  /*ff*/ipMapHomeS/*ff*/                  ; /*ff*//**//*ff*/
struct  /*ff*/sexHeadS/*ff*/                    ; /*ff*//**//*ff*/
class   /*ff*/sexC/*ff*/                        ; /*ff*//**//*ff*/
class   /*ff*/slotsC/*ff*/                      ; /*ff*//**//*ff*/
class   /*ff*/poolC/*ff*/                       ; /*ff*//**//*ff*/
class   /*ff*/puseC/*ff*/                       ; /*ff*//**//*ff*/
class   /*ff*/fileC/*ff*/                       ; /*ff*//**//*ff*/
class   /*ff*/grabitC/*ff*/                     ; /*ff*//**//*ff*/
class   /*ff*/grabotC/*ff*/                     ; /*ff*//**//*ff*/
class   /*ff*/linkedC/*ff*/                     ; /*ff*//**//*ff*/
struct  /*ff*/listingC/*ff*/                    ; /*ff*//**//*ff*/
class   /*ff*/listC/*ff*/                       ; /*ff*//**//*ff*/
class   /*ff*/datumC/*ff*/                      ; /*ff*//**//*ff*/
class   /*ff*/datum_countT_C/*ff*/              ; /*ff*//**//*ff*/
class   /*ff*/listing_countT_C/*ff*/            ; /*ff*//**//*ff*/
class   /*ff*/datum_blob_C/*ff*/                ; /*ff*//**//*ff*/
class   /*ff*/datum_countTstrz_C/*ff*/          ; /*ff*//**//*ff*/
class   /*ff*/listing_blob_C/*ff*/              ; /*ff*//**//*ff*/
class   /*ff*/list_countT_C/*ff*/               ; /*ff*//**//*ff*/
class   /*ff*/list_blob_C/*ff*/                 ; /*ff*//**//*ff*/
struct  /*ff*/listWalkArgOldS/*ff*/             ; /*ff*//**//*ff*/
class   /*ff*/baseGrabC/*ff*/                   ; /*ff*//**//*ff*/
struct  /*ff*/tellInfoSysAdamFiredS/*ff*/          ; /*ff*//**//*ff*/
struct  /*ff*/sexGlobalEntryS/*ff*/             ; /*ff*//**//*ff*/
struct  /*ff*/subaccountS/*ff*/                 ; /*ff*//**//*ff*/
class   /*ff*/pbC/*ff*/                         ; /*ff*//**//*ff*/
class   /*ff*/psttC/*ff*/                       ; /*ff*//**//*ff*/
struct  /*ff*/accountS/*ff*/                    ; /*ff*//**//*ff*/
struct  /*ff*/depositS/*ff*/                    ; /*ff*//**//*ff*/
class   /*ff*/stkIdSubC/*ff*/                   ; /*ff*//**//*ff*/
class   /*ff*/bucketTotalC/*ff*/                ; /*ff*//**//*ff*/
class   /*ff*/bucketDetailC/*ff*/               ; /*ff*//**//*ff*/
struct  /*ff*/depositDetailS/*ff*/              ; /*ff*//**//*ff*/
struct  /*ff*/bookHeadS/*ff*/                   ; /*ff*//**//*ff*/
class   /*ff*/book0C/*ff*/                      ; /*ff*//**//*ff*/
class   /*ff*/bookC/*ff*/                       ; /*ff*//**//*ff*/
class   /*ff*/booksC/*ff*/                      ; /*ff*//**//*ff*/
class   /*ff*/pageC/*ff*/                       ; /*ff*//**//*ff*/
class   /*ff*/branchPageC/*ff*/                 ; /*ff*//**//*ff*/
class   /*ff*/jotC/*ff*/                        ; /*ff*//**//*ff*/
struct  /*ff*/monitorS/*ff*/                    ; /*ff*//**//*ff*/
struct  /*ff*/fireGroupS/*ff*/                  ; /*ff*//**//*ff*/
struct  /*ff*/doC/*ff*/                         ; /*ff*//**//*ff*/
class   /*ff*/refCounterC/*ff*/                 ; /*ff*//**//*ff*/
class   /*ff*/refC/*ff*/                        ; /*ff*//**//*ff*/
class   /*ff*/httpReplyRefC/*ff*/              ; /*ff*//**//*ff*/
class   /*ff*/pbRefC/*ff*/                      ; /*ff*//**//*ff*/
struct  /*ff*/storeReplyPrivateF_argS/*ff*/     ; /*ff*//**//*ff*/
class   /*ff*/blobVSP/*ff*/                     ; /*ff*//**//*ff*/
struct  /*ff*/fieldEditParamInC/*ff*/           ; /*ff*//**//*ff*/
struct  /*ff*/fieldEditParamOutC/*ff*/          ; /*ff*//**//*ff*/
class   /*ff*/listing_countTstrz_C/*ff*/        ; /*ff*//**//*ff*/
class   /*ff*/list_countTstrz_C/*ff*/           ; /*ff*//**//*ff*/
class   /*ff*/listingVSP/*ff*/                  ; /*ff*//**//*ff*/
class   /*ff*/datum_listingVSP_C/*ff*/          ; /*ff*//**//*ff*/
class   /*ff*/listing_listingVSP_C/*ff*/        ; /*ff*//**//*ff*/
class   /*ff*/list_listingVSP_C/*ff*/           ; /*ff*//**//*ff*/
struct  /*ff*/parm_tmAdamMainF_S/*ff*/          ; /*ff*//**//*ff*/
struct  /*ff*/slabS/*ff*/                       ; /*ff*//**//*ff*/
class   /*ff*/cleanC/*ff*/                      ; /*ff*//**//*ff*/
struct  /*ff*/whereS/*ff*/                      ; /*ff*//**//*ff*/
struct  /*ff*/featuresS/*ff*/                   ; /*ff*//**//*ff*/
struct  /*ff*/strikeS/*ff*/                     ; /*ff*//**//*ff*/
class   /*ff*/sadamC/*ff*/                      ; /*ff*//**//*ff*/
class   /*ff*/sadamsC/*ff*/                     ; /*ff*//**//*ff*/
struct  /*ff*/cPoint2S/*ff*/                    ; /*ff*//**//*ff*/
class   /*ff*/deviceC/*ff*/                     ; /*ff*//**//*ff*/
class   /*ff*/displayC/*ff*/                    ; /*ff*//**//*ff*/
struct  /*ff*/displayArgS/*ff*/                 ; /*ff*//**//*ff*/
class   /*ff*/eyeC/*ff*/                        ; /*ff*//**//*ff*/
struct  /*ff*/glyphTallyS/*ff*/                 ; /*ff*//**//*ff*/
struct  /*ff*/mPoint3S/*ff*/                    ; /*ff*//**//*ff*/
class   /*ff*/paperC/*ff*/                      ; /*ff*//**//*ff*/
struct  /*ff*/paperS/*ff*/                      ; /*ff*//**//*ff*/
class   /*ff*/pelC/*ff*/                        ; /*ff*//**//*ff*/
struct  /*ff*/pelS/*ff*/                        ; /*ff*//**//*ff*/
class   /*ff*/spaceC/*ff*/                      ; /*ff*//**//*ff*/
struct  /*ff*/surfC/*ff*/                       ; /*ff*//**//*ff*/
struct  /*ff*/spaceS/*ff*/                      ; /*ff*//**//*ff*/
class   /*ff*/associateC/*ff*/                  ; /*ff*//**//*ff*/
class   /*ff*/assViewC/*ff*/                    ; /*ff*//**//*ff*/
struct  /*ff*/assViewStqS/*ff*/                 ; /*ff*//**//*ff*/
struct  /*ff*/assViewEyeS/*ff*/                 ; /*ff*//**//*ff*/
struct  /*ff*/drawJobS/*ff*/                    ; /*ff*//**//*ff*/
class   /*ff*/vector3C/*ff*/                    ; /*ff*//**//*ff*/
class   /*ff*/matrix3C/*ff*/                    ; /*ff*//**//*ff*/
class   /*ff*/barryC/*ff*/                      ; /*ff*//**//*ff*/
struct  /*ff*/htmlS/*ff*/                       ; /*ff*//**//*ff*/
class   /*ff*/hasherC/*ff*/                     ; /*ff*//**//*ff*/
struct  /*ff*/cloudInfoS/*ff*/                  ; /*ff*//**//*ff*/
struct  /*ff*/rParam_new_S/*ff*/                ; /*ff*//**//*ff*/
struct  /*ff*/bitNodeS/*ff*/                    ; /*ff*//**//*ff*/
class   /*ff*/bitTreeC/*ff*/                    ; /*ff*//**//*ff*/
class   /*ff*/cloudC/*ff*/                      ; /*ff*//**//*ff*/
class   /*ff*/napkinsC/*ff*/                    ; /*ff*//**//*ff*/
class   /*ff*/heapC/*ff*/                       ; /*ff*//**//*ff*/
class   /*ff*/fileWindowC/*ff*/                 ; /*ff*//**//*ff*/
class   /*ff*/fileWindowsC/*ff*/                ; /*ff*//**//*ff*/
class   /*ff*/hoverC/*ff*/                      ; /*ff*//**//*ff*/
class   /*ff*/patternC/*ff*/                    ; /*ff*//**//*ff*/
class   /*ff*/fileNameC/*ff*/                   ; /*ff*//**//*ff*/
struct  /*ff*/diskFindHandleS/*ff*/             ; /*ff*//**//*ff*/
struct  /*ff*/cachedS/*ff*/                     ; /*ff*//**//*ff*/
class   /*ff*/cacheC/*ff*/                      ; /*ff*//**//*ff*/
class   /*ff*/inOutFrameC/*ff*/                 ; /*ff*//**//*ff*/
struct  /*ff*/taskDrivenServerJobS/*ff*/     ; /*ff*//**//*ff*/

//INCLUDE GENERATED SNIPPETS HERE

#include "\ideafarm.home.1\precious\domains\com\ideafarm\city\library\snip\1snip.0050010.gen_CsOURCEfILES.h"


//
// Respecting the rights of other people is an important part of empowering one another.
// This proprietary software was crafted at great expense and with great hardship by one man.  It took 28 years.
//
// Copyright (c) 1992-2020 Wo Of Ideafarm.  All rights reserved.  See IDEAFARM.COM for permitted uses.
//

